  
name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 9 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.4'
    - name: Test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: go test -v .
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Dependency scan
      uses: snyk/actions/golang@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
